version: '3.8'

networks:
  transfer-network:
    driver: bridge

services:
  transfer-db:
    image: postgres:14.1-alpine
    container_name: transfer-db
    restart: always
    environment:
      POSTGRES_DB: transfer-db
      POSTGRES_USER: ${TRANSFER_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${TRANSFER_DB_PASSWORD:-postgres}
    ports:
      - "5438:5432"
    networks:
      - transfer-network
    logging:
      driver: "json-file"
      options:
        max-size: 50m

  transfer-backend:
    image: ghcr.io/nekromant322/transfer-backend:latest
    container_name: transfer-backend
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT:-5438}/b
    ports:
      - "9001:8080"
    networks:
      - transfer-network
    logging:
      driver: "json-file"
      options:
        max-size: 50m
    depends_on:
      - transfer-db

  transfer-frontend:
    image: ghcr.io/nekromant322/transfer-frontend:latest
    container_name: transfer-frontend
    restart: unless-stopped
    ports:
      - "9002:8080"
    networks:
      - transfer-network
    logging:
      driver: "json-file"
      options:
        max-size: 50m