telegram:
  token: {TG_BOT_TOKEN}


server:
  port: 8080

spring:
  config:
    import: classpath:cities.yml
  application:
    name: transfer
  datasource:
    password: ${POSTGRES_PASSWORD:-postgres}
    username: ${POSTGRES_USER:-postgres}
    url: jdbc:postgresql://${DB_HOST:-localhost}:${DB_PORT:-5432}/transfer_db
    driver-class-name: org.postgresql.Driver