telegram:
  token: ${TG_BOT_TOKEN}
  username: ${TG_BOT_USERNAME}


server:
  port: 8080

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:}

google:
  sheets:
    prices-url: https://docs.google.com/spreadsheets/d/1Lwk-XBSU32uO6lxfq2jR8BFKrFlUWGEaK32NOu8Prbk/export?format=csv&gid=0

spring:
  config:
    import: classpath:cities.yml
  application:
    name: transfer
  datasource:
    password: ${POSTGRES_PASSWORD:postgres}
    username: ${POSTGRES_USER:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/transfer_db
    driver-class-name: org.postgresql.Driver